name: sln comile

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: CSC
      run: |
        csc "C#\zone-user-login-msg.cs"
        dir "C#"

    - uses: actions/upload-artifact@v3
      with:
        name: csc-compile
        path: ${{ github.workspace }}\zone-user-login-msg.exe # or path/to/artifact
